version: "2"

services:
  mongo_:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
      - ./database-user.js:/docker-entrypoint-initdb.d/001-user.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: osemadmin
      MONGO_INITDB_ROOT_PASSWORD: SecretPass
      MONGO_INITDB_DATABASE: osem-api-db
    command: --storageEngine wiredTiger
    networks:
      - api-back
    restart: always
    labels:
      org.opensensemap.watchtower.enable: "true"
