version: "2"

services:
  mongo_:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbOSeMUser
      MONGO_INITDB_ROOT_PASSWORD: securePaSs
    command: --storageEngine wiredTiger
    networks:
      - api-back
    restart: always
    labels:
      org.opensensemap.watchtower.enable: "true"
